apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
replicas: 2
selector:
  matchLabels:
  app: myapp
template:
  metadata:
    labels:
      app: myapp
  spec:
    containers:
      - name: cont-1
        image: nginx
        ports:
          - containerPort: 80
