apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
replicas: 2
selector:
  matchLabels:
  app: myapp1
template:
  metadata:
    labels:
      app: myapp1
  spec:
    containers:
      - name: cont-1
        image: shaikmustafa/dm
        ports:
          - containerPort: 80
